# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
print(f"Random Tensor {tensor}\n")

print(f"Shape of tensor: {tensor.shape}\n")
print(f"Datatype of tensor: {tensor.dtype}\n")
print(f"Device tensor in stored on: {tensor.device}\n")

Random Tensor tensor([[0.1617, 0.2227, 0.5891, 0.8301, 0.3410, 0.4013, 0.9018],
        [0.5875, 0.9391, 0.9447, 0.6825, 0.7848, 0.1450, 0.8846],
        [0.9752, 0.4254, 0.7497, 0.7953, 0.7117, 0.7866, 0.4868],
        [0.6512, 0.9864, 0.6324, 0.6081, 0.1977, 0.1901, 0.3149],
        [0.5682, 0.1472, 0.1774, 0.2036, 0.6820, 0.5909, 0.0941],
        [0.7573, 0.4065, 0.9695, 0.2450, 0.9866, 0.6615, 0.1458],
        [0.2833, 0.3405, 0.7367, 0.5010, 0.6834, 0.7469, 0.3337]])

Shape of tensor: torch.Size([7, 7])

Datatype of tensor: torch.float32

Device tensor in stored on: cpu



### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor

tensor2 = torch.rand(1,7)

# Perform matrix multiplication
torch.matmul(tensor, tensor2.T)


tensor([[1.7751],
        [2.6720],
        [2.8176],
        [1.9928],
        [1.4638],
        [2.1845],
        [1.7623]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor, tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():

    # Create two random tensors on GPU
    tensor3 = torch.rand(2,3).to("cuda")
    tensor4 = torch.rand(2,3).to("cuda")

print(tensor)
print(tensor2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
mult = torch.matmul(tensor3, tensor4.T)
print(mult)
print(mult.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(mult.max())

# Find min
print(mult.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(mult.argmax())

# Find arg min
print(mult.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor5 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor6 = tensor5.squeeze()

# Print out tensors and their shapes
print(tensor5, tensor5.shape)
print(tensor6, tensor6.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
